---
output: word_document
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "Output_Documents") })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning =  FALSE)
knitr::opts_chunk$set(results = 'asis')
source("global.R")

Groups <- Species_Info |> 
  dplyr::filter(ScientificName %in% c(Benthic_Biomass_Species, Fish_Biomass_Species)) |> 
  dplyr::select(Classification, ScientificName, CommonName, Trophic_Broad, Targeted_Broad) |> 
  dplyr::mutate(CommonName = gsub(", adult", "", CommonName),
                CommonName = gsub(", male", "", CommonName),
                CommonName = gsub("[(>)]", "", CommonName),
                CommonName = gsub(" 1m", "", CommonName)) |> 
  dplyr::distinct(ScientificName, .keep_all = TRUE) |> 
  dplyr::arrange(Classification, Trophic_Broad, Targeted_Broad) |> 
  dplyr::rename(`Scientific Name` = ScientificName, 
                `Common Name` = CommonName, 
                `Fishery Status` = Targeted_Broad, 
                `Trophic Level` = Trophic_Broad)


Fish_Regression_Table <- readr::read_csv("Meta_Data/Fish_Regression.csv")

Benthic_Regression_Table <- readr::read_csv("Meta_Data/Benthic_Regression.csv")
```

```{r Trophic Interaction GLMMs, fig.height=10.5, fig.width=7.5}

options(scipen = 999)

purps <- car::Anova(
  test = "F",
  lme4::lmer(
    data = Mixed_2005,
    purple_sea_urchin ~ California_spiny_lobster * California_sheephead_male * California_sheephead_female * sunflower_star * giant_spined_sea_star + 
      IslandCode + (1 | SurveyYear))) |> 
  base::as.data.frame() |> 
  tibble::rownames_to_column(var = "Predictor Variable") |> 
  dplyr::arrange(`Pr(>F)`) |> 
  dplyr::mutate(`F` = round(`F`, 3),
                `Pr(>F)` = round(`Pr(>F)`, 3),
                `Pr(>F)` = ifelse(`Pr(>F)` < 0.001, "< 0.001", as.character(`Pr(>F)`))) |> 
  dplyr::rename(`P-Value` =`Pr(>F)`) |> 
  dplyr::select(-Df.res)
knitr::kable(purps)

reds <- car::Anova(
  test = "F",
  lme4::lmer(
    data = Mixed_2005,
    red_sea_urchin ~ California_spiny_lobster * California_sheephead_male * California_sheephead_female * sunflower_star * giant_spined_sea_star + 
      IslandCode + (1 | SurveyYear))) |> 
  base::as.data.frame() |> 
  tibble::rownames_to_column(var = "Predictor Variable") |> 
  dplyr::arrange(`Pr(>F)`) |> 
  dplyr::mutate(`F` = round(`F`, 3),
                `Pr(>F)` = round(`Pr(>F)`, 3),
                `Pr(>F)` = ifelse(`Pr(>F)` < 0.001, "< 0.001", as.character(`Pr(>F)`))) |> 
  dplyr::rename(`P-Value` =`Pr(>F)`) |> 
  dplyr::select(-Df.res)
knitr::kable(reds)


whites <- car::Anova(
  test = "F",
  lme4::lmer(
    data = Mixed_2005,
    white_sea_urchin ~ California_spiny_lobster * California_sheephead_male * California_sheephead_female * sunflower_star * giant_spined_sea_star + 
      IslandCode + (1 | SurveyYear))) |> 
  base::as.data.frame() |> 
  tibble::rownames_to_column(var = "Predictor Variable") |> 
  dplyr::arrange(`Pr(>F)`) |> 
  dplyr::mutate(`F` = round(`F`, 3),
                `Pr(>F)` = round(`Pr(>F)`, 3),
                `Pr(>F)` = ifelse(`Pr(>F)` < 0.001, "< 0.001", as.character(`Pr(>F)`))) |> 
  dplyr::rename(`P-Value` =`Pr(>F)`) |> 
  dplyr::select(-Df.res)
knitr::kable(whites)

kelp <- car::Anova(
  test = "F",
  lme4::lmer(
    data = Mixed_2005,
    giant_kelp ~ California_spiny_lobster * California_sheephead_male * California_sheephead_female * sunflower_star * giant_spined_sea_star + 
      white_sea_urchin * red_sea_urchin * purple_sea_urchin +
      IslandCode + (1 | SurveyYear))) |> 
  base::as.data.frame() |> 
  tibble::rownames_to_column(var = "Predictor Variable") |> 
  dplyr::arrange(`Pr(>F)`) |> 
  dplyr::mutate(`F` = round(`F`, 3),
                `Pr(>F)` = round(`Pr(>F)`, 3),
                `Pr(>F)` = ifelse(`Pr(>F)` < 0.001, "< 0.001", as.character(`Pr(>F)`))) |> 
  dplyr::rename(`P-Value` =`Pr(>F)`) |> 
  dplyr::select(-Df.res)
knitr::kable(kelp)

```

```{r GLMM Tables, results = 'asis'}
# Make me a loop with all relevant tables
GLMM <- GLMM_Results %>% 
  dplyr::filter(`Response Variable` == "shannon_2005") |> 
  dplyr::select(-`Response Variable`, -`VIF Score`)
knitr::kable(GLMM)
```

```{r}
GLMM_Vars <- c("shannon_2005",
               "simpson_2005",
               "warty_sea_cucumber",
               "Kellets_whelk",
               "California_spiny_lobster",
               "white_sea_urchin",
               "garibaldi",
               "orange_puffball_sponge",
               "bladder_chain_kelp",
               "red_sea_urchin",
               "California_sheephead_male",
               "bat_star",
               "giant_kelp",
               "purple_sea_urchin",
               "kelp_bass",
               "sunflower_star",
               "giant_spined_sea_star",
               "Coronado_urchin",
               "red_abalone",
               "rock_wrasse")

for (rv in GLMM_Vars) {
  
  print(rv)
  
  GLMM <- GLMM_Results %>% 
    dplyr::filter(`Response Variable` == rv) |> 
    dplyr::select(-`Response Variable`, -`VIF Score`)
  print(knitr::kable(GLMM))
}
```

```{r Groups}
knitr::kable(Groups)
```

```{r RF Important Species}
RF_VI <- RF_Importance %>%  
  dplyr::mutate(CommonName = gsub("B", "", CommonName),
                CommonName = gsub("C", "", CommonName),
                CommonName = gsub("P", "", CommonName),
                CommonName = gsub("I", "", CommonName),
                CommonName = gsub("Cg", "", CommonName),
                CommonName = gsub("[()]", "", CommonName),
                Rank = order(desc(MeanDecreaseAccuracy))) |> 
  dplyr::select(Rank, ScientificName, CommonName, Data_Type, 
                Targeted, MeanDecreaseAccuracy, MeanDecreaseGini) |> 
  dplyr::rename(`Scientific Name` = ScientificName, 
                `Common Name` = CommonName, 
                `Fishery Status` = Targeted, 
                `Data Type` = Data_Type)
knitr::kable(RF_VI)
```

```{r Regression Values}
knitr::kable(Fish_Regression_Table) 
knitr::kable(Benthic_Regression_Table) 
```





